mosdef-hub/foyer

foyer/forcefield.py

forcefield.registerAtomType() was creating a new element with the mass
that ParmEd was passing it, which is a string. The mass was converted to
a floating point number in the function, but that was not what was
passed to simtk.openmm.app.element.Element().  This was causing errors
in the hoomdxml writer when trying to divide by the reference mass
(since hoomd uses reduced units).

Create new element with mass as float, not string

---

docs/smarts.md
foyer/forcefields/oplsaa.xml
foyer/smarts.py

The previous code mistook 'R' to mean ring size which is actually
denoted by 'r'.
See http://www.daylight.com/dayhtml/doc/theory/theory.smarts.html

Fix incorrect interpretation of ring size token

---

foyer/forcefield.py

Angles and dihedrals were already ordered by the index of the first
atom, but bonds were not. This ordering is typically not important,
but can apparently cause some issues in some downstream software.
Should resolve mosdef-hub/mbuild#273

Order bonds in Structure by index of first atom

---

devtools/conda-recipe/meta.yaml
environment.yml
examples/ethane.py
foyer/forcefield.py
foyer/forcefields/oplsaa.xml
foyer/tests/test_forcefield.py

A `doi` attribute can now be included in force field XML files.  The doi references for all atom types in a structure can be printed to a JSON file by providing an additional argument to `apply`.

Include DOI references in force field XML files

---

foyer/forcefield.py
foyer/tests/test_forcefield.py

1. Applicable to mBuild Compounds
* converts to parmed structure first( which will either accept a custom box, or None)
* if none, will pad all dimensions by 0.5nm.
* alleviates the error when atom typing with a < 3dimensional box
Fixes #105

Fix when passing in a compound with a bounding box < 3 dimensions

---

foyer/smarts_graph.py
foyer/tests/test_graph.py
foyer/tests/test_smarts.py

* Only perform graph matching starting with the first atom_expression in a SMARTS
* Only run rules on specified elements when possible
* Currently no optimization is performed for rules that contain a not_expression or contain multiple atom_symbols in the first atom_expression

Optimizations to graph matching

---

docs/usage_examples.md
foyer/forcefield.py
foyer/tests/test_forcefield.py

This preserves residue information during atomtyping.  Previously all atoms were lumped into a single residue.

Pass residue information from Parmed Structure to OpenMM Topology

---

foyer/forcefields/oplsaa.xml
foyer/version.py

The "class" on opls_151, opls_152, and opls_153 SMARTS strings were updated.  This should fix missing bond information for alkyl chlorides.

Changed "class" for atomtypes 151, 152, 153 on 'oplsaa.xml'

---

foyer/atomtyper.py

Added a pre-processing step in ```find_atomtypes``` that internally throws out rules based on atomtypes not found in the system and reduces the size of the ```rules``` dictionary accordingly. For example, if you were atomtyping alkanes with OPLS, it would remove rules considering N, O, F, etc. before atomtyping. This does not, however, modify the ```Forcefield``` itself because the user may wish to re-use that forcefield for a system that contains a different set of unique elements.

Slice out "rules" for elements not found in system

---

foyer/smarts_graph.py

Only keep track of cycles atoms are in if the cycles contain less than 8 atoms (if we feel there is a need to make this number larger we can certainly do so).  This helps to speed up the atom-typing process so that Foyer isn't spending time looping over cycles that may be thousands of atoms long, such as in the case of a surface.

Limiting cycle size to less than 8 atoms

---

foyer/forcefield.py
foyer/tests/test_forcefield.py

Big thanks to @summeraz and @justinGilmer for codemonkey-ing this out.
Currently, each residue in a system is atomtyped even if an identical residue was previously atomtyped. For example, the current atomtyper would atomtype each water in a million-water system, which is a waste of time for larger systems. The approach here is to create a map of unique, already-atomtyped residues, so the 2nd to Nth residue don't call the subgraph isomorphism routines and instead look back at a prototype that was added to the map when it was first found.
* It appears to not be possible to slice ```openmm.app.Topology``` so I wrote a helper function that takes a ```openmm.app.Topology.Residue``` and returns an otherwise-identical ```openmm.app.Topology```. This could be done cleaner if slicing is …

Avoid duplicate residue atomptying

---

.travis.yml

There is an issue wth homebrew and the ruby version on osx that
causes homebrew to fail for all travis builds currently.
Forcing homebrew to update before installing packages fixes this issue.

Fix homebrew Ruby error

---

foyer/smarts_graph.py
foyer/validator.py

Several functions and function names have changed from NetworkX 1.0 to NetworkX 2.0. For example, the `Graph.nodes_iter()` function has been replaced by `Graph.nodes()`. This PR changes our NetworkX syntax to conform to both versions.

NetworkX migration

---

.travis.yml

rvm has issues with shell_session_update
osx does not have this by default.
updating to a newer version of rvm seems to fix for many groups

Another travis fix for osx

---

foyer/forcefield.py
foyer/validator.py

Previously, when applying a forcefield with many missing atom types
in the forcefield XML, `foyer` would output as a warning all the
missing atom types to the user upon successfully atom typing.
For the larger forcefield files (`oplsaa.xml` for example), there are currently
~750 missing atom types that do not have a smarts string. This led to cumbersome
warning messages.
Now, the default behavior for missing atom types is to still warn the user, but
condense the information to ~2 lines of output.
If the user wants to know which atom types are missing a smarts string,
a debug flag can be passed during the application of the forcefield to
revert to the previous behavior.

Quiet output for missing atom types

---

foyer/forcefield.py
foyer/tests/test_forcefield.py

The `_check_independent_residues` function, which needs to be `True` in order to use the residue map feature I added a while back, breaks if the atoms in the residue have no bond partners. The function checks to see if any bond partners of atoms in a given residue are not themselves atom in said residue:
```
if set(atoms_in_residue) != set(bond_partners_in_residue):
return False
```
But this was breaking when `bond_partners_in_residue` is an empty list.
This small fix handles this case, and should allow single-atom residues to use the residue map for speedup in atomtyping.
h/t @justinGilmer, who found this by way of an argon system that was slow to apply a force field to.

Allow single-atom residues to use the residue map

---

foyer/tests/utils.py

See some of the early comments in  #153 
I skimmed the rest of the repo for `opls` in variable names [link](https://github.com/mosdef-hub/foyer/search?l=Python&q=opls&type=&utf8=%E2%9C%93) but didn't find anything else in Python files.

Make some variables and messages not specific to OPLS

---

foyer/forcefield.py
foyer/tests/test_forcefield.py

Dicussed in #157, but to repeat the important bit:
Currently there's a bit of code at the beginning of `Forcefield.createSystem` that manages the atomtyping step, whereas this should more cleanly done by being sectioned off to a different function.
* I'm open to naming the function something more elegant, I'm not happy with `Forcefield.run_atomtyping` but couldn't come up with something better.
* I'm not sure if it should be a helper function, or whatever `Forcefield._run_atomtyping` would be called. It seems possible for a user to want to call it directly without creating the entire `openmm.System` or `parmed.Structure`.
* I don't think a test is necessary for this, as I'm just moving code around. But I also couldn't think of how a useful test would be structured. I could verify that the …

Move atomtyping step into a specific function

---

MANIFEST.in
foyer/forcefield.py
foyer/tests/files/ethane-multi.bib
foyer/tests/files/refs-multi.xml
foyer/tests/test_forcefield.py

Currently the `doi` attribute for atomtypes defined in a force field XML file only supports a single DOI. However, there may be instances where multiple DOIs would be appropriate (see #158). This PR adds support for listing multiple DOIs within the `doi` attribute, and passes this information through to the BibTeX file that is created.

Multiple DOIs per atomtype

---

foyer/forcefield.py
foyer/tests/files/overrides-space.xml
foyer/tests/test_forcefield.py

Currently multiple atomtype names can be listed within a single `overrides` attribute for an atomtype definition in a force field XML file, but these must be separated by a comma only and no space, e.g. `overrides="opls_1,opls_2"`.
This PR updates this behavior to allow for spaces between atomtype names, e.g. `overrides="opls_1, opls_2"`.

Add support for overrides definitions with spaces

---

.gitignore

Using Microsoft's VSCode generates an addtional directory
and files to assist the various plugins, save states, etc.
This is not needed for other users.
This has been added to the .gitignore file to prevent these files from
being committed erroneously.

Ignore VSCode project and setup files

---

foyer/tests/test_performance.py

This should pass CI, fixing a single issue with #199:
```
_________________________________________________________ test_surface __________________________________________________________
@pytest.mark.timeout(15)
def test_surface():
surface = mb.load(get_fn('silica.mol2'))
forcefield = Forcefield(get_fn('opls-silica.xml'))
>       forcefield.apply(surface, assert_bond_params=True, debug=True)
foyer/tests/test_performance.py:20: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
foyer/forcefield.py:409: in apply
_error_or_warn(assert_bond_params, msg)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
error = True, msg = 'Parameters …
```

Allow for some missing silica bond parameters

---

appveyor.yml

It's starting to give me problems (see the mess of #228) so I think it's time to just drop it. Note that the Python 3 builds on Appveyor and Python 2.7 builds on Travis have been passing.
Arguably this is an opportunity to drop it from Travis too, but I would prefer keeping it along until it gives us non-trivial-to-fix problems.

Drop Python 2.7 testing from Appveyor

---

devtools/conda-recipe/meta.yaml

We previously switched mbuild over and it seems to be working fine.
Advantages:
* we don't need to do `conda convert` when building packages for anaconda
* a user on a version of Python we don't explicitly support, i.e. Python 3.7, could try to install it with less work than building from source
h/t @mikemhenry

Switch conda recipe to noarch

---

devtools/conda-recipe/meta.yaml
foyer/smarts_graph.py
requirements-dev.txt
requirements.txt

See #226 for discussion and #205 for context. `boltons` seems to be a light dep but there doesn't seem to be a compelling reason to need order/indexing/etc in the whitelist blacklist. Maybe it could help in debugging but that part of the package seems pretty stable now.
Probably squash & merge this one, or I can clean up the git history.

Use built-in sets for whitelists & blacklists

---

foyer/forcefields/oplsaa.xml

@mikemhenry pointed out in #221 that a carbon atom had an incorrect mass.
This has been fixed.
------------
closes #221

Carbon with incorrect mass

---

foyer/tests/files/oplsaa-periodic.xml
foyer/tests/files/oplsaa_multiperiodicitytorsion.xml
foyer/tests/test_forcefield.py
foyer/xml_writer.py

#239 This code modifies the XML writer to look for multiple periodictorsionforces that apply to the same dihedrals. This is done by comparing the "current" periodic dihedral to the "previous" periodic dihedral, and determining whether the two dihedral forces should be merged into one. 
As a side note, the issues with the DOI XMLprinting should have been appropriately addressed in #161, any issues we saw with the DOI XMLprinting were due to flaws in the "source" FFXML we were using to parametrize these structures, not in how we were printing to the "sink" FFXML
------------

Periodictorsions xml

---

foyer/tests/conftest.py
foyer/tests/test_forcefield.py

Same idea as #242 but using @ctk3b's suggestion of `@pytest.fixture(scope="session")`
Can't really verify on CI that the extraneous files aren't being written, but they're not in my local directory. Somebody else should grab these changes and runs tests to see that it works for them as well.
------------

Add conftest.py to store pytest fixtures

---

README.md

The gitter badge on the README was using a non-scalable graphics format (`png`). This has been updated to a vector graphic (`svg`) which now scales based on resolution.
------------

Use vector graphic instead of png

---

foyer/forcefield.py
foyer/validator.py

Change the temporary file creation from `tempfile.mkstemp` to
`tempfile.NamedTemporaryFile`.
`mkstemp` creates a temporary file with a file handle that can be
accessed in a secure manner, preventing possible race conditions.
However, `mkstemp` also requires _manual_ deletion of the file
after its purpose has been served.
This file was never being deleted, and would pollute the `$TMPDIR`
of the user who was running `Foyer`.
Instances of `mkstemp` have been replaced with `NamedTemporaryFile`,
which provides a higher level interface to created temp files,
and all instances where these are used are captured in `try,finally`
blocks, to ensure that they are removed after the XML files have been
processed.
Resolves #244 
------------

Enforce deletion of temporary XML files

---

.travis.yml
docs/installation.rst

Bye Felicia
#200 
Also updated the installation docs, mostly copying from mbuild. Not sure what else can/should be dropped, maybe codecov will find some things?
------------

Drop Python 2.7 from travis and docs

---

foyer/tests/test_forcefield.py
foyer/tests/test_performance.py

Fixes #271 .
Adds some pytest skips for `has_mbuild=False`
Also, before this PR, `import mbuild` as well as `mbuild.Alkanes` was located at the top of the function. This could be unsafe for testing? Although my first guess is that importing mbuild could be dangerous and circular. If we're careful in mbuild, mbuild shouldn't be importing foyer anywhere, so foyer could haphazardly import mbuild (though we should try to clean away any foyer-importing-mbuild)
------------

Mbuild imports

---

foyer/tests/test_utils.py
foyer/utils/nbfixes.py

Implements #267 
@zijiewu3 this might be a more formal way of doing what we suggested for your cross-interactions, feel free to give this a shot or suggest any changes
------------

Add workaround function for applying nbfixes

---

foyer/atomtyper.py

Upgrading to networkX >= 2.4 removes the nx.Graph.node method, breaking
atomtyper.py.
NetworkX recently updated to 2.4 and the way we access nodes have been
removed: G.node –> use G.nodes. This was only present in `atomtyper.py`,
the rest of our node calls were using the new syntax.
Updating to handle the new syntax restores expected behavior, and all
unit tests pass.
------------
Addresses issue #279

Update atomtyper.py to use networkX 2.X methods

---

README.md

We dropped it in March (https://github.com/mosdef-hub/foyer/commit/3bb74d5a4a1ec0a6cce5a7c9ea92cf5675bc2a4f) soon after we were happy with codecov and therefore it hasn't had any data since then. I'll also make sure the app is uninstalled.
Opening as a PR so I can check the rendered markdown looks ok
------------

Remove coveralls badge from README

---

foyer/forcefields/forcefields.py
foyer/tests/test_plugin.py
foyer/tests/test_validator.py
setup.py

Small change post-#282 per suggestions of @uppittu11 and @ahy3nz https://github.com/mosdef-hub/foyer/pull/282#issuecomment-547144491 https://github.com/mosdef-hub/forcefield_perfluoroethers/pull/4/files#r339807274
Instead of the entrypoint being an instance of the force field, it's a function that grabs it. This cleans up the import such that the user more discretely instantiates the object. It also prevents the loading from happening upon `import foyer` and should save some time on imports. A quick local check saved ~0.3 seconds, no promises this is accurate.
------------

Switch entrypoints to functions that load classes

---

foyer/forcefield.py

Reorder the codes for `_check_angles`. Right now, even if `verbose=True`, the corresponding block of code will not be excuted because of the `_error_or_warn` line right before it. 
------------

`_check_angles` bug fix

---

foyer/forcefield.py
foyer/tests/test_forcefield.py

This is another way of separating out the parametrization steps and wrapping them up into a single function. 
Similar to #286 except the user would call `system = FF. parametrize_system(top, pos)` instead of `FF.apply()`:
```python3
>>> import mbuild as mb
>>> ethane = mb.load('CC', smiles=True).to_parmed()
//anaconda3/envs/mosdef-dev/lib/python3.7/site-packages/openbabel/__init__.py:14: UserWarning: "import openbabel" is deprecated, instead use "from openbabel import openbabel"
warnings.warn('"import openbabel" is deprecated, instead use "from openbabel import openbabel"')
/Users/mwt/software/mbuild/mbuild/compound.py:2714: UserWarning: No unitcell detected for pybel.Molecule CC	
warn("No unitcell detected for pybel.Molecule {}".format(pybel_mol))
>>> import foyer
>>> oplsaa = …
```

Move parametrization steps into a discrete function

---

devtools/travis-ci/install_conda.sh

This is a very minor change to download `Minconda` using `curl` rather than `wget`. The errrored builds we are getting is due to `wget` and `openssl` paths. Using `curl` resolves this.
Travis build for this branch can be tracked [here](https://travis-ci.org/umesh-timalsina/foyer/jobs/616827616).

Fix Travis Build Erros

---

foyer/forcefield.py

Fixes https://github.com/mosdef-hub/mbuild/issues/645. This may fix the AZP ❌ but not the travis ❌ 
All I did was pass the `assert_improper_params` to the `self.parametrize_system` call, as @ahy3nz found and I neglected earlier.
------------

Pass assert_improper_params to paramtrize_system

---

foyer/forcefield.py
foyer/forcefields/ff.xsd
foyer/tests/files/lj.xml
foyer/tests/files/lj2.xml
foyer/tests/test_forcefield.py

Fixes  #187, would be useful in  #290 
* Adds `version` as an attribute of the `ForceField` element in the XML schema
* Adds `version` as an attribute to the `Forcefield` class
* Adds a simple test via reading a toy XML file and asserting the above two `version`s are equal
This is not done elegantly right now; 99% of the XML loading is done by OpenMM, so I had to do this after the fact and only dealing with the case of passing a single XML, which is all I believe we do right now. I'm not sure what the target for this PR should be, but I think we should soon have a bigger discussion about how we want to handle multiple XML files. The OpenMM use case is basically `Forcefield('protein_model.xml', 'water_model.xml')`, i.e. there is a clean interface between constituents and not any expected …

Add version attribute to force fields

---

devtools/travis-ci/install_conda.sh

See https://github.com/mosdef-hub/mbuild/issues/723

Fix conda url in travis

---

foyer/forcefield.py

This is relate to a few recent issues posted.
https://github.com/mosdef-hub/foyer/issues/326
https://github.com/mosdef-hub/foyer/issues/323
1) There was a coding issue in the part of the code that would write out a missing RB dihedral when in verbose mode (undefined parameters referenced).  Also, only ids were being output, not types (inconsistent with, e.g., how angles were outputted).   The coding and formatting issues have been addressed. 
2) Even when fixing that coding/formatting issues, the code only checked the RB torsions. So, when I was testing periodic torsions, it alerted that all dihedrals were missing.    This bit now has two loops, first looping over proper_dihedrals and then rb_torsions in parmed structure. 
------------

fixed error in verbose mode for missing dihedrals

---

foyer/smarts_graph.py
requirements-dev.txt
requirements.txt

self.ast.find_data('atom') destroys the original order of atoms in a SMARTSGraph. Since later on, the first atom is used for atom-typing, it was causing an error. The following keeps the order:
[x for x in self.ast.iter_subtrees_topdown() if x.data == 'atom']
------------

find_data in lark

---

foyer/forcefield.py
foyer/tests/test_forcefield.py

Relate to #336. Add a warning if a typed structure has non-zero charge. 'np.allclose()' is used instead of '==' to check for 0 equivalence so since some system may have insignificant non-zero net charge (like 1e-16).
------------

Add warning for non-zero charge structure

---

devtools/conda-recipe/meta.yaml

To ensure that we have our plugins supported properly when installed
from conda, it appears that a few options are necessary to ensure that
is the case.
For the case of setuptools entry_points, the conda-build documentation
recommends that we do include the build option: preserve_egg_dir
https://docs.conda.io/projects/conda-build/en/latest/user-guide/recipes/build-without-recipe.html#preserve-egg-directory
Setuptools are also now build and runtime dependencies.
------------

Entrypoints conda

---

foyer/atomtyper.py
foyer/smarts_graph.py
foyer/tests/test_graph.py

Looking at https://github.com/mosdef-hub/foyer/pull/348, I'm concerned there's a lot of spaghetti code to handle both parmed and gmso objects. I think for some "upstream" foyer processing, it might be an important stopgap to accommodate both objects, but a lot of the downstream graph matching code within foyer's `smarts_graph.py` shouldn't have to change. Namely, generalize the properties of the topological graph's nodes to be more "primitive" properties (like index, symbol, number, n_bond_partners) instead of the node's singular property being a bulky parmed atom (or gmso site) which contains the relevant properties. This PR tries to address this:
* Rework `smarts_graph.find_matches` so the properties of the topological graph are the primitive properties of each atom, not a parmed atom …

Boil down graph

---

foyer/forcefield.py

I think I found this typo in `forcefield.py`: 
```       
if not all([a.id for a in structure.atoms][0]):
raise ValueError('Not all atoms in topology have atom types')
```
I think that `[0]` should not be there since it kills the purpose of `all()`. 
------------

Fix typo in forcefield.py

---

README.md

The link to docker tutorial was not rendering correctly in README, this PR fixes it.

Fix docker link in README

---

README.md

change badge from `mosdef` channel to `conda-forge` channel in README.

Update status badge for anaconda cloud

---

foyer/forcefield.py
foyer/tests/test_plugin.py

This PR adds a `get_available_forcefield_loaders` function, which returns a list of the functions returning `Forcefield` objects as discovered by the plugin system. I believe there is no other way to systematically access these function in the current API, i.e. from inside Foyer and not the package that plugs into it. In the past I have either called entry points I had in short-term memory or tab-completed `foyer.forcefields.load_` in an interpreter.
------------

Add get_available_forcefield_loaders

---

foyer/forcefields/forcefields.py
foyer/forcefields/xml/CHANGELOG.md
foyer/forcefields/xml/oplsaa.xml
foyer/forcefields/xml/trappe-ua.xml

fixes #363 and fixes #340
- Added names and versions to OPLS-AA and TRAPPE-UA
- Added a warnings wrapper to the load functions because the remaining warnings are very unhelpful to users:
```
>>> ff = foyer.forcefields.load_TRAPPE_UA()
/Users/jenny/Projects/foyer/foyer/forcefield.py:526: UserWarning: Non-atomistic element type detected. Creating custom element for _CH4
warnings.warn('Non-atomistic element type detected. '
/Users/jenny/Projects/foyer/foyer/forcefield.py:526: UserWarning: Non-atomistic element type detected. Creating custom element for _CH3
warnings.warn('Non-atomistic element type detected. '
/Users/jenny/Projects/foyer/foyer/forcefield.py:526: UserWarning: Non-atomistic element type detected. Creating custom element for _CH2
warnings.warn('Non-atomistic element type …
```

Stop built in FF's from throwing warnings

---

azure-pipelines.yml
environment-dev-win.yml
environment-dev.yml
environment-win.yml
environment.yml

* As is, `environment.yml` does not work because the `requests` package is missing.
* `environment-win.yml` is really a development environment `environment-dev-win.yml`. This file was renamed.
* There is no windows equivalent of `environment.yml`. This has been added.
Right now, creating an development environment with `environment.yml` cause the `GAFF foyer` tests to error: `AttributeError: module 'foyer.forcefields.forcefields' has no attribute 'load_GAFF'`. ~~At first I thought this was because GAFF foyer is installed before foyer. Wasn't there some issue with this @justinGilmer @umesh-timalsina. However, I tried re-installing GAFF foyer before foyer so now I am less certain what has gone wrong.~~ If possible, I would also like to get that fixed before we merge this PR.
**Edit**:  The …

Update conda yaml files to be more consistent and bug fix

---

Dockerfile

With the new additions of the conda env yml files to our repo, this
inevitably added some unforeseen issues with our release pipeline.
This fixes the case where our docker images would not build, since the
environment-dev.yml file has a `pip:` section that needs to clone a
repository using `git`. `git` is not installed by default in the alpine
docker image, and has been added to the `RUN` command.
------------

Include git in docker image to clone repo

---

environment-dev-win.yml
environment-dev.yml
environment-win.yml
environment.yml

Closes #414. 
`networkx 2.3` on `python 3.9` has an issue where it errors on import. I was getting `2.3` by default on `osx`.

Pin networkx>=2.5

---

README.md

Since we have stopped publishing new release to Pypi, the version on there is quite obsolete. And with the new breaking change, the pypi version of foyer may not work as expected for user, so I think we should remove the pypi badge to avoid confusion. Similar to https://github.com/mosdef-hub/mbuild/pull/912
------------

Remove pypi badge from readme

---

foyer/forcefield.py
foyer/tests/test_forcefield.py

Previously, the tests in test_forcefield.py were assumed to test that
forcefield metadata like `version`, `name`, etc. were properly loaded
into the `Forcefield` object.
This is only partially true, as there are cases where the files either
go out of scope before that information is gathered, etc. This PR
includes additional tests to ensure that this information is not being
lost prematurely. Big thanks to: @mattwthompson, @ahy3nz for discovering
this issue, creating MWE's for some of these cases, and taking my
investigation further and most likely pinpointing the issue.
------------
Refer to issues/PRs: #433 #434 
Note: This does not have @ahy3nz 's fix incorporated yet, just the test cases that fail and currently work.

Include detailed tests for forcefield metadata

---

.pre-commit-config.yaml

I made a typo when trying to add an exclusion for precommit yml, which lead to fail precommit test. This PR fix that typo. 
------------

Fix typo in precommit yml

---

Dockerfile
azure-pipelines.yml

Previously, all conda environment creations use conda for the
dependency resolution, which is notoriously slower than mamba's
implementation.
This can have a noticeable impact on run times during CI as well as
building docker images. Mamba has replaced conda in our dockerfile as
well as our azurepipelines.yml file.
NOTE: mamba is not used for windows builds, due to previous issues
attempting to use mamba.
------------

Migrate azure pipeline environment creation from conda to mamba

---

foyer/forcefields/xml/CHANGELOG.md
foyer/forcefields/xml/oplsaa.xml
foyer/tests/test_forcefield.py
foyer/tests/test_opls.py

Update definition of `opls_154` in `oplsaa.xml`, raised by #438. Tests were updated accordingly. 
------------

Update smarts string for opls_154

---

README.md
docs/docs-env.yml
environment-dev-win.yml
environment-dev.yml
environment-win.yml
environment.yml
foyer/element.py
foyer/forcefield.py

This PR removes all the simtk references for openmm imports and should be merged after https://github.com/ParmEd/ParmEd/issues/1185 is resolved. Tests will fail for the timebeing.

Remove simtk references for openmm 7.6

---

Dockerfile

Previously, the latest version of miniconda3 alpine docker image was incorrectly built as a debian image. This has now been fixed.
However, in between the previous version we have been using, the anaconda user was not added by default. I added the necessary adduser commands to fix this.
------------
Closes #453

Update docker image and re-add anaconda user

---

azure-pipelines.yml

https://docs.codecov.com/docs/about-the-codecov-bash-uploader#deprecation-notice-and-schedule 
Suggests that the bash uploader we use will be deprecated soon. This PR uses the recommended codecov uploader to upload coverage reports.
------------

Use codecov uploader in favor of bash uploader for coverage reports

---

foyer/forcefield.py
foyer/tests/test_forcefield_parameters.py

See #470 for further details. Previously, we didn't return any parameters if the value of `k == 0`. This PR attempts to fix that. Resolves #470.
------------

Return periodic torsion params, regardless of k value

---

foyer/forcefield.py

Fixes #485 
Adds printout of missing bond types.
------------

Report missing bonds' types when using verbose flag

---

README.md
foyer/general_forcefield.py
foyer/tests/files/gmso_spce_water.xml
foyer/tests/test_gmso_forcefield.py
foyer/tests/test_validator.py

Add validation step to perform XML conversion only if foyer XML is provided (else load directly by gmso).
------------

Modify XML parsing order of general forcefield

---

foyer/general_forcefield.py

Currently, when perform atomtyping with `general_forcefield.Forcefield`, the `combining_rule` and `scaling_factors` are not being transferred correctly. This PR makes sure the `scaling_factors` is passed correctly to the final `gmso.Topology`. The `combining_rule` can be specified during the `Forcefield.apply()` called, but I just realized that the `combining_rule` is not an attribute of GMSO Forcefield, so that will be implemented in a separate PR (in GMSO). 
------------

Fix scaling factors and mixing rule bug when atomtype with `general_forcefield` 

---

foyer/forcefield.py
foyer/tests/test_forcefield.py

Relate to #495. Start storing meta data like combining rule and scaling factors in parametrized parmed structure. Currently utilizing the `_Defaults` class from `parmed.gromacs.gromacstop` so terminology may be GROMACS specific, but the info can be stored and access there. 
------------

Storing meta data in pmd structure

---

CITATION.cff

GitHub has added native support of the CITATION.cff file format, which
provides a nice way to generate a citation for a software repository.
This adds in a basic citation.cff file, which can be updated as
necessary.
------------

Add CITATION.cff file for easier repo citation

---

.readthedocs.yml
docs/docs-env.yml

After #513, RTD builds are failing. This may be due to the docs environment being pinned to a (now) unsupported Python version. You'd think I would have noticed that after looking at the files off and on for months, but you'd be wrong.
This PR updates that and gives Mambaforge a try (Micromamba isn't [supported](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python) yet).
------------

Update docs environment to use Python 3.8+

---

.github/workflows/CI.yaml

Right now, if what of the check failed, all the other unfinished checks will get canceled, which miss the point of testing on different OS. This PR turns that off. Similar to https://github.com/mosdef-hub/mbuild/pull/1067
------------

Turn off fail-fast

---

.pre-commit-config.yaml
foyer/utils/nbfixes.py

Resolves #529 
By using deepcopy() in foyer.utils.nbfixes.apply_nbfix, the parmed structure loses the following attributes ['links', 'symmetry', 'defaults']. Without links, there is an error when copying the structure in mbuild.lammpsdata.
File ".....mbuild/mbuild/formats/lammpsdata.py", line 170, in write_lammpsdata
structure = structure.copy(cls=Structure, split_dihedrals=True)
File ".....python3.8/site-packages/parmed/structure.py", line 613, in copy
for l in self.links:
------------

Update nbfix to use parmed structure.copy

---

foyer/forcefield.py
foyer/tests/test_utils.py
foyer/utils/nbfixes.py

Address https://github.com/mosdef-hub/mbuild/issues/1111. Change the default of `use_residue_map` in `Forcefield.apply` to `False`, since this may be produced unexpected behavior if users try to atomtype of systems with similar residue name. 
------------

change default of use_residue_map to be False

---

environment-dev.yml
foyer/topology_graph.py

`Topology.topology_atoms` was deprecated in 0.11.0 and will be removed in the forthcoming 0.14.0 release.
------------

Do not use deprecated OpenFF Toolkit iterator

---

.github/workflows/CI.yaml
environment-dev-win.yml
environment-dev.yml
environment-win.yml
foyer/topology_graph.py

A change I made to the toolkit (https://github.com/openforcefield/openff-toolkit/pull/1661) involved changing how attributes are looked up, which made this check
```
uses_old_api = hasattr(Topology(), "_topology_molecules")
```
no longer produce the same behavior as when I wrote it. With 0.14.4, released last night, this line erroneously evaluates to `True`. There would be a few ways to fix this, but I'm proposing to just remove the dual support. We are no longer supporting the "old" (< 0.11) versions of the toolkit. Note, of course, that this change wouldn't affect any released version of Foyer.
I also noticed tests aren't run in parallel - it's a small and straightforward fix to get CI to use the multiple cores that [GHA provides …

Do not use 'old' OpenFF Toolkit API

---

.github/workflows/CI.yaml

We again bumped into unknown error for windows py3.8 test, probably similar to that seen windows py3.9. This PR will temporarily drop the test for windows py3.8 CI run. 
------------

Drop Testing for py38 in Windows

---

foyer/atomtyper.py

Slight change in error string to provide guidance to a user on how to resolve it.
------------
- [NA] Includes appropriate unit test(s)
- [NA] Appropriate docstring(s) are added/updated
- [NA] Code is (approximately) PEP8 compliant
- [NA] Issue(s) raised/addressed?

Clarify error in applying forcefield

---

.github/workflows/CI.yaml
environment-dev-win.yml
environment-dev.yml
environment-win.yml
environment.yml
foyer/tests/files/ethane_customtype.pdb
foyer/tests/test_forcefield.py

mBuild and GMSO have started testing with python 3.12 and both versions of MacOS, we should do that here as well.
------------

add python 3.12 and macOS-13 to test matrix

---

.pre-commit-config.yaml
docs/source/conf.py
foyer/atomtyper.py
foyer/forcefield.py
foyer/smarts_graph.py
foyer/tests/base_test.py
foyer/tests/test_atomtyping.py
foyer/tests/test_forcefield.py
foyer/tests/test_forcefield_parameters.py
foyer/tests/test_graph.py
foyer/tests/test_opls.py
foyer/tests/test_plugin.py
foyer/tests/test_smarts.py
foyer/tests/test_topology_graph.py
foyer/tests/test_utils.py
foyer/tests/utils.py
foyer/topology_graph.py
foyer/utils/io.py
foyer/utils/nbfixes.py
foyer/validator.py
foyer/xml_writer.py
setup.py

This PR does the same as https://github.com/mosdef-hub/gmso/pull/819 in GMSO
closes #572 
------------

Add ruff to pre-commit hooks

---

environment-dev.yml
foyer/forcefield.py

This PR ensures XML files are opened in UTF-8 mode while being processed. The background here is ... messy and hard to reproduce. What I'm fairly sure of is that my testing infrastructure writes some temporary files (including Foyer XML files) and something might be loaded under an assumption of ASCII encoding. This causes a crash similar to forcing that behavior:
```python
>>> open('oplsaa.xml', encoding='ascii').read()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/mattthompson/micromamba/envs/new-models/lib/python3.11/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 56770: ordinal not in range(128)
``` …

Ensure XML files are opened with UTF-8 encoding

---

codecov.yaml
docs/docs-env.yml
docs/source/conf.py

The doc builds were failing with sphinx>=8.0. This PR fixes the source of the error.
------------

Fix documentation build
