- foyer/forcefield.py
> Fix mass bug

- devtools/conda-recipe/meta.yaml
Setting the USERNAME environment variable  in meta.yaml to fix a bug in Appveyor
> Appveyor bug fix

- MANIFEST.in
- foyer/forcefield.py
- foyer/tests/files/ethane_customtype.pdb
- foyer/tests/files/validate_customtypes.xml
- foyer/tests/test_forcefield.py
- setup.py
Read custom atom types from pdb, correctly create elements based on element names in non_element_types
> Parmed customelement fix

- foyer/forcefields/ff.xsd
- foyer/tests/files/benzene.mol2
- foyer/tests/files/improper_dihedral.xml
- foyer/tests/test_forcefield.py
Figured it was easier to start fresh than fix
> Add Improper in xsd

- .travis.yml
It appears that travis is having some
issues again.
This is an issue with `rvm` hopefully this fixes it.
> Attempt to fix `shell session update` error

- appveyor.yml
- devtools/conda-recipe/meta.yaml
- requirements.txt
> Pin OpenMM to < 7.3

- appveyor.yml
Same change as in https://github.com/mosdef-hub/mbuild/pull/477 🤞
> Run `activate base` before `conda build` in Appveyor

- foyer/forcefield.py
- foyer/tests/test_forcefield.py
> Add check for force field missing definitions

- .travis.yml
- devtools/conda-recipe/meta.yaml
- foyer/forcefield.py
- foyer/tests/test_forcefield.py
- foyer/tests/test_performance.py
- foyer/utils/io.py
- requirements-dev.txt
- requirements.txt
Mirrors mosdef-hub/mbuild#457 
h/t @justinGilmer
> Remove mbuild as a normal dependency

- devtools/conda-recipe/meta.yaml
- requirements-dev.txt
- requirements.txt
> Clean up some dependencies

- devtools/conda-recipe/meta.yaml
- foyer/atomtyper.py
- foyer/smarts.py
- foyer/smarts_graph.py
- foyer/tests/test_graph.py
- foyer/tests/test_performance.py
- foyer/tests/test_smarts.py
- foyer/validator.py
- requirements-dev.txt
- requirements.txt
This is the initial version of migrating to the [`lark` parser](https://github.com/lark-parser/lark) form [`plyplus`](https://github.com/erezsh/plyplus) (#172).
> Migrate to lark parser

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/QUESTION.md
- .github/PULL_REQUEST_TEMPLATE.md
We tend to make good changes in mbuild (https://github.com/mosdef-hub/mbuild/pull/498) and forget to do them here ...
> Add some issue/PR templates

- CONTRIBUTING.md
Mostly the same as in mbuild (https://github.com/mosdef-hub/mbuild/pull/500)
> Add a contributor's guide

- .travis.yml
- README.md
- codecov.yaml
- requirements-dev.txt
Trying to duplicate https://github.com/mosdef-hub/mbuild/pull/485
> Add codecov basics

- .travis.yml
- appveyor.yml
- devtools/conda-recipe/meta.yaml
- foyer/forcefield.py
- foyer/tests/test_forcefield.py
- requirements-dev.txt
- requirements.txt
This PR attempts to build and test on Python 3.7. It is built off of #246 to fix an OpenMM compatibility issue and mirrors https://github.com/mosdef-hub/mbuild/pull/542
------------
> Support Python 3.7

- README.md
- docs/citing_foyer.rst
- docs/files/foyer_citation.bib
- docs/files/foyer_citation.ris
- docs/index.rst
The paper is online so I have updated the links. As usual you can see the rendered file on my fork: https://github.com/mattwthompson/foyer/blob/cite-paper/README.md
Not sure if any references in the proper docs need to be updated? I poked around briefly and didn't find anything.
------------
> Update links for COMMAT paper

- foyer/atomtyper.py
- foyer/forcefield.py
- foyer/smarts_graph.py
- foyer/tests/test_forcefield.py
- foyer/tests/test_graph.py
- foyer/tests/test_smarts.py
Implements @ctk3b's idea in #233
Not all tests are passing (some residue map and override stuff needs to be updated) but the basic cases are handled.
------------
>  Store atomtyping results in a dict instead of the topology

- docs/paper_examples.rst
- docs/usage_examples.rst
- foyer/examples/files/modify_oplsa_silica.py
- foyer/examples/files/opls-silica.xml
- foyer/examples/files/oplsaa_alkane.xml
- foyer/examples/files/oplsaa_with_silica.xml
- foyer/examples/files/output.xml
- foyer/examples/utils.py
- foyer/tests/utils.py
- setup.py
Update Foyer docs with current mbuild organization, refer to #265. 
------------
> Foyer docs udpate

- foyer/atomtyper.py
- foyer/forcefield.py
- foyer/validator.py
- foyer/xml_writer.py
Added some docstrings and other small fixes
------------
> Docathon changes

- README.md
- azure-pipelines.yml
Adding Azure Pipelines as a new CI.
This is a draft PR for azure pipelines integration with foyer.
------------
> Azure Pipelines as CI

- foyer/__init__.py
- foyer/examples/files/modify_oplsa_silica.py
- foyer/smarts_graph.py
- foyer/utils/nbfixes.py
- foyer/validator.py
Mirrors https://github.com/mosdef-hub/mbuild/pull/616 and checks to see if LGTM behaves well here
------------
> Add some style fixes suggested by LGTM

- devtools/conda-recipe/meta.yaml
- foyer/tests/test_forcefield.py
- foyer/tests/utils.py
- requirements-dev.txt
Fixes #211, unlike my crash of an attempt in #212
CI might take some negotiation
------------
> Mock requests in tests

- foyer/forcefield.py
- foyer/tests/test_forcefield.py
- foyer/tests/test_opls.py
Implements the quick-and-dirty fix to #284 
------------
> Set the default combining rule to be geometric

- .travis.yml
- foyer/tests/test_forcefield.py
Should help #302 
------------
> Refactor tests using mbuild examples to using mbuild recipes

- .travis.yml
Same as https://github.com/mosdef-hub/mbuild/pull/660
> Don't install md5sha1sum

- azure-pipelines.yml
After deleting and creating a new foyer pipeline on AZP, I noticed that the daily builds are no longer scheduled.  Making a PR with small change for the purpose of triggering the scheduled builds.
------------
> Try and trigger AZP scheduled builds

- devtools/conda-recipe/meta.yaml
- docs/docs-env.yml
- requirements-dev.txt
- requirements.txt
Removed six, which is now an unused dependency.
------------
> Removed six from requirements.

- MANIFEST.in
Same as https://github.com/mosdef-hub/mbuild/pull/701
> Add LICENSE.rst to MANIFEST.in

- foyer/atomtyper.py
- foyer/smarts_graph.py
The final goal of this PR is to add GMSO as another backend for foyer. This is still a WIP, more updates will be posted in the comment as I progress. 
------------
> GMSO integration 

- README.md
The link to the documentation on foyer README is outdated and lead to a 404, so I am just updating the working link in this PR.
------------
> Update foyer docs link

- docs/_templates/footer.html
>  Add link to github/homepage in docs footer 

- docs/conf.py
> Update copyright years in docs (Closes #352)

- foyer/forcefield.py
> Solved the typo(des to desc)

- requirements-dev.txt
- requirements.txt
Pin OpenMM to 7.5 to par with the new fix in #369. 
------------
> Pin OpenMM to 7.5

- docs/paper_examples.rst
- docs/usage_examples.rst
Closes #375. Thanks to @bkpgh.
> Update usage documentation

- azure-pipelines.yml
> Remove '--no-coverage-upload flag', does not exist anymore

- azure-pipelines.yml
Uploading `codecov` reports without using tokens.
> Upload Codecov reports without tokens

- foyer/forcefield.py
- foyer/tests/test_forcefield_parameters.py
> Add lj14scale and coulomb14scale to Forcefield

- foyer/forcefields/xml/oplsaa.xml
- foyer/opls_validation/chloride/chloride.gro
- foyer/opls_validation/chloride/chloride.top
- foyer/tests/implemented_opls_tests.txt
Closes #401.
Added smarts definition for a single chloride ion together with @daico007 and @justinGilmer.
> Add SMARTS definition for a single chloride ion

- README.md
Add a small paragraph in readme mentioning the TRUE paper.
------------
> Include TRUE in readme

- .pre-commit-config.yaml
Previously, when we introduced pre-commit, it required users to manually
run the pre-commit hook locally.
Now, these pre-commit features can be run in the cloud now, which can be
useful for users that might not want to install the required packages.
This introduces the yaml configuration necessary to autoformat PRs
according to our current configuration.
------------
> Allow pre-commit to autoupdate prs

- foyer/tests/test_gmso_forcefield.py
At the moment, loading in large forcefield XML files so that GMSO can
be used as the backend data structure has some performance issues.
This introduces a fixture called `oplsaa` which loads the oplsaa.xml
forcefield once and can be used wherever needed in the
`test_gmso_forcefield.py`. This currently reduces
the entire testing time from 573 seconds to 348 seconds. I used:
`time python -m pytest -v foyer/tests`
------------
> Reduce testing time for gmso implementation

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
Minor fix to issue template to allow sample run to run correctly
------------
> Fix typo in issue template

- azure-pipelines.yml
- environment-dev-win.yml
- environment-dev.yml
- environment.yml
Similar to https://github.com/mosdef-hub/mbuild/pull/982. This PR modify the azure bleeding test to work with the latest mbuild and gmso commit. 
------------
> Modify bleeding test

- README.md
> Add note explaining the origin of the name "foyer"

- environment-dev-win.yml
- environment-dev.yml
- foyer/tests/test_performance.py
- foyer/tests/test_utils.py
I still haven't been able to identify the culprit, so I gonna take more like a trial-error approach here. 
------------
> Attempting to fix failing CI
